### ISSUE TITLE
Showing a commit should include the full commit id at the top

### ISSUE THREAD

**Issue by nedbat** [tpope/vim-fugitive#933] opened 2017-08-02 19:28 UTC
From the :Gblame window, I select a line, and hit enter on the commit id.  This opens the commit in a new buffer.

The top of the buffer has four lines: tree, parent, author, committer.  It would be very handy to have the full commit id in that header also.

**Comment by chrisbra** [comment] 2017-08-21 12:59
duplicate of #857

**Closed** 2017-08-28 23:12 UTC
