### ISSUE TITLE
Gdiff splits wrong window

### ISSUE THREAD

**Issue by jpmv27** [tpope/vim-fugitive#853] opened 2016-11-02 11:40 UTC
After the following sequence of commands:

1) :Gstatus
2) 'D' on some changed file in status window
3) Differences are displayes
3) 'U' on same file in status window to discard changes
4) re-load file at vim prompt
5) status pane updates
6) 'D' on some other changed file in status window

At this point, the Gdiff splits the status window instead of the file window

**Comment by notantonia** [comment] 2017-03-13 22:45
I'm experiencing the same issue.

**Comment by sinisterstuf** [comment] 2017-08-26 21:00
Looks like the same issue to me. Perhaps this should be closed as a duplicate and further discussion continued there?

**Comment by dhruvasagar** [comment] 2017-10-06 18:25
I believe this is likely a duplicate as indicated, and am unable to reproduce it.

**Comment by godefv** [comment] 2019-01-17 16:07
I have this issue after a very recent update. I did not have it before.

**Closed** 2019-02-02 18:02 UTC
