### ISSUE TITLE
Unpushed sections in the status buffer

### ISSUE THREAD

**Issue by x-yuri** [tpope/vim-fugitive#2106] opened 2023-01-21 11:40 UTC
This one is actually a follow-up on #1436 to a degree, but I feel like it makes sense to start a new issue.

I was thinking about the status buffer, and how it doesn't always show what I need... But let me start from the bottom, so to say:

https://github.com/tpope/vim-fugitive/blob/23b9b9b2a3b88bdefee8dfd1126efb91e34e1a57/autoload/fugitive.vim#L2894-L2902

The way I understand it... One can probably say that `pull` and `push` are `pull` source and `push` destination. `pull` is empty if there's no `@{upstream}`. `push` is empty when not on any branch or when `push.default == upstream` and no `@{upstream}`.

The first section (`$push..HEAD`) is shown when `push` destination and `pull` source don't match or they match but there are unpushed commits. `len(push)` is a safeguard against `push` being empty.

The preconditions:

* on a branch
* `push.default != upstream` or `@{upstream}`
* `push !=# pull` or there are unpushed commits

The second section (`$pull..HEAD`) is shown when `push` destination and `pull` source don't match. `len(pull)` is again a safeguard against `pull` being empty.

The preconditions:

* `@{upstream}`
* `push !=# pull`

The third section is shown when `push` and `pull` are empty. (Let's leave rebasing out of the discussion.)

The preconditions:

* no `@{upstream}`
* not on a branch or `push.default == upstream` and no `@{upstream}`

One can see that the first and second sections are not mutually exclusive. Particularly they're be both shown when:

* on a branch
* `@{upstream}`
* `push !=# pull`

Is this by design or by accident? I don't see a case where one might need 2 unpushed sections. Unless someone pushes code in both or several directions?.. O.o

A couple of minor issues here, which are probably not really important, but I can't help but point out. The `push` and `pull` variables... the names are rather obscure. `if len(pull) && push !=# pull`? I don't think anyone can figure out what it means unless he/she knows what they hold. And even in that case that sounds confusing. I'd suggest `pull_src`/`push_dst`/`pull_branch`/`push_branch` or something.

Also this way it looks more readable to me:

```diff
-if len(push) && !(push ==# pull && get(props, 'branch.ab') =~# '^+0 ')
+if len(push) && (push !=# pull || get(props, 'branch.ab') !~# '^+0 ')
```

Although I now see a way to justify it.

Now, let's take one step up. Let's say I start a project locally, make some commits (the [script][a]):

```sh
mkcommit() { echo "$1" > "$1" && git add "$1" && git commit -m "$1"; }
mkdir a
cd a
git init
mkcommit a
vim +'e .git/index'
```

but they don't appear in the status buffer because there are no remotes, no `@{upstream}`, no nothing... Well, actually the first section "tries" to appear, but `git log origin/master..master` exits with an error. And I don't think I like that. Not because of the exit code, but because I'd expect `empty(pull) && empty(push)` in this case (but [`push ==# 'origin/master'`][m]). Which kind of makes sense if we're deciding where to push code, but not when we're considering the situation at hand.

A simple solution that comes to mind is to make the third section appear:

```diff
-if empty(pull) && empty(push) && empty(rebasing)
+let has_remotes = len(filter(keys(config), 'v:val =~# "^remote\\.[^.]\\+\\.url$"'))
+if empty(pull) && (empty(push) || !has_remotes) && empty(rebasing)
   call s:AddLogSection('Unpushed to *', [head, '--not', '--remotes'])
 endif
```

A slightly more involved one: make `push`, `push_remote`, `fetch_remote` (and potentially more) empty in this case.

There's also a workaround (or rather a hack) for a user — set `push.default = upstream` (the [script][b]):

```sh
echo -e '[push]
\tdefault = upstream' >> .git/config
vim +'e .git/index'
```

Now, let's say I have a remote and all, and am starting a branch (the [script][c]):

```sh
mkdir a
(cd a
git init
mkcommit a
)
git clone a a2
(cd a2
git checkout -b fb
mkcommit b
vim +'e .git/index'
)
```

Again no unpushed section.

One solution is to push an empty commit to the branch (the [script][d]):

```sh
(cd a2
git checkout -b fb
git commit --allow-empty -m to-delete
git push origin fb
mkcommit b
vim +'e .git/index'
)
```

Another solution is to set upstream to `origin/master` and `push.default = current` (upstream is `origin/master`, but push to `origin/fb`, the [script][e]):

```sh
(cd a2
echo -e '[push]
\tdefault = current' >> .git/config
git checkout -b fb @{upstream}
mkcommit b
vim +'e .git/index'
)
```

Then the unpushed section lists the `b` commit, and `git push` pushes `fb` to `origin/fb` (owing to `push.default = current`), not to `origin/master`.

`branch.autoSetupMerge=always` won't help here because it'll set `branch.fb.remote = .`, and `git push` will be trying to push `fb` to `fb`, and happily telling that everything is up-to-date.

Now, let's push a commit and create another one (the [script][f]):

```sh
(cd a2
echo -e '[push]
\tdefault = current' >> .git/config
git checkout -b fb @{upstream}
mkcommit b
git push
mkcommit c
vim +'e .git/index'
)
```

In this case `fugitive` shows two unpushed sections: the first one with `c` (the unpushed commit) and the second one with `b` and `c`. That's the case mentioned above. And at least at first glance that's unhelpful and confusing here.

To sum it up:

* You might want to set `push.default = upstream` when starting a new repository to see commits when there are no remotes.
* After adding a remote it makes sense to set `push.default = current` and create branches with `git checkout -b BRANCH @{upstream}` (upstream is `origin/master`, but push to `origin/BRANCH`).
* After you push the branch you will occasionally see two unpushed sections (when you have unpushed commits).
* `git push -u` will set upstream to `origin/BRANCH` and you'll be left only with unpushed commits (no two unpushed sections).

That's is kind of tricky. At least the no-remotes case should be dealt with, I think.

And the last step is that what I actually want to see is all the commits in a branch (possibly up to some limit). But that sounds like a major change. And I might be the only one needing it. Maybe because I care about commit history too much (often rewrite it). Well, unless I need to push a branch, it sounds bearable. Make `push !=# pull`, and you get all the branch's commits. But sometimes I need to push a branch (to trigger the build or something). Sometimes I need to rewrite history beyond the unpushed commits after having pushed the branch. I didn't pay much attention to it, but I know that I occasionally don't see the needed commits in the status buffer.

Let's say we decide to replace the unpushed/unpulled sections with one section. If we're on `master` and there're no remotes, than it makes sense to show all the commits. Or introduce an optional setting (e.g. `branch.NAME.fugitive_log_since` or something). If there are remotes, then only unpushed ones. When on an ordinary branch, all the branch's commits. That brings up the question about the name of the `master` branch. Which might be resolved with another setting (e.g. `fugitive.master`). But this (new) behavior might not be in line with common workflows. I mean I don't know for sure, but I assume that most people are content with the current behavior and that maybe I'm doing it an unusual way. What do you think?

[a]: https://gist.github.com/x-yuri/68204bef6f1b4ede195450b1a091064d#file-a-sh
[b]: https://gist.github.com/x-yuri/68204bef6f1b4ede195450b1a091064d#file-b-sh
[c]: https://gist.github.com/x-yuri/68204bef6f1b4ede195450b1a091064d#file-c-sh
[d]: https://gist.github.com/x-yuri/68204bef6f1b4ede195450b1a091064d#file-d-sh
[e]: https://gist.github.com/x-yuri/68204bef6f1b4ede195450b1a091064d#file-e-sh
[f]: https://gist.github.com/x-yuri/68204bef6f1b4ede195450b1a091064d#file-f-sh
[m]: https://github.com/tpope/vim-fugitive/blob/2febbe1f00be04f16daa6464cb39214a8566ec4b/autoload/fugitive.vim#L2825

**Comment by tpope** [comment] 2023-01-23 07:28
I don't have time for an exhaustive reply; instead i will play whack-a-mole and leave it to you to follow-up on anything important I missed.

> There's also a workaround (or rather a hack) for a user — set `push.default = upstream` (the [script](https://gist.github.com/x-yuri/68204bef6f1b4ede195450b1a091064d#file-b-sh)):

I can't reproduce this. It's definitely not the intended behavior. I don't think anyone should set `push.default = upstream` (but if you do, it makes sense for Fugitive to alter the status in a way that reflects the altered behavior of `git push`).

> One can see that the first and second sections are not mutually exclusive. Particularly they're be both shown when:
> 
> * on a branch
> * `@{upstream}`
> * `push !=# pull`
> 
> Is this by design or by accident? I don't see a case where one might need 2 unpushed sections. Unless someone pushes code in both or several directions?.. O.o

It's very deliberate. I explicitly added it in response to our discussion in https://github.com/tpope/vim-fugitive/issues/1436#issuecomment-578461381.

> In this case `fugitive` shows two unpushed sections: the first one with `c` (the unpushed commit) and the second one with `b` and `c`. That's the case mentioned above. And at least at first glance that's unhelpful and confusing here.

`c` is what hasn't been pushed to your feature branch. `b` and `c` are what haven't been merged into `origin/master`. Seems helpful and straightforward to me? Maybe it will seem clearer if you imagine the section "Unpushed" section is labeled "Unmerged".

> but they don't appear in the status buffer because there are no remotes, no `@{upstream}`, no nothing... Well, actually the first section "tries" to appear, but `git log origin/master..master` exits with an error. And I don't think I like that. Not because of the exit code, but because I'd expect `empty(pull) && empty(push)` in this case (but [`push ==# 'origin/master'`](https://github.com/tpope/vim-fugitive/blob/2febbe1f00be04f16daa6464cb39214a8566ec4b/autoload/fugitive.vim#L2825)). Which kind of makes sense if we're deciding where to push code, but not when we're considering the situation at hand.
> 
> A simple solution that comes to mind is to make the third section appear:
> 
> ```diff
> -if empty(pull) && empty(push) && empty(rebasing)
> +let has_remotes = len(filter(keys(config), 'v:val =~# "^remote\\.[^.]\\+\\.url$"'))
> +if empty(pull) && (empty(push) || !has_remotes) && empty(rebasing)
>    call s:AddLogSection('Unpushed to *', [head, '--not', '--remotes'])
>  endif
> ```

I haven't fully thought it through, but a possibly viable approach here would be to avoid the `origin` default if no `origin` remote exists. That is, alter this conditional:

https://github.com/tpope/vim-fugitive/blob/2febbe1f00be04f16daa6464cb39214a8566ec4b/autoload/fugitive.vim#L2811-L2813

**Closed by tpope** 2023-01-23 07:28 UTC

**Comment by x-yuri** [comment] 2023-02-15 06:12
Sorry for the wall of text. There were these related issues, and I failed to express it more concisely.

Let's take it one step at a time. In a repository with no remotes:

```sh
set -eu
mkcommit() { echo "$1" > "$1" && git add "$1" && git commit -m "$1"; }
mkdir a
cd a
git init
mkcommit a
vim +'e .git/index'
```

`fugitive` doesn't show unpushed sections. One solution:

```diff
-if empty(pull) && empty(push) && empty(rebasing)
+let has_remotes = len(filter(keys(config), 'v:val =~# "^remote\\.[^.]\\+\\.url$"'))
+if empty(pull) && (empty(push) || !has_remotes) && empty(rebasing)
   call s:AddLogSection('Unpushed to *', [head, '--not', '--remotes'])
 endif
```

Not sure what you meant by altering the `if empty(fetch_remote)` conditional:

https://github.com/tpope/vim-fugitive/blob/2febbe1f00be04f16daa6464cb39214a8566ec4b/autoload/fugitive.vim#L2806-L2816

But `fetch_remote ==# ''` -> `push ==# '/master'`, `fetch_remote ==# '.'` (which is a weird default) -> `push ==# 'master'`:

https://github.com/tpope/vim-fugitive/blob/2febbe1f00be04f16daa6464cb39214a8566ec4b/autoload/fugitive.vim#L2818-L2826

And that doesn't let the third section to appear:

https://github.com/tpope/vim-fugitive/blob/2febbe1f00be04f16daa6464cb39214a8566ec4b/autoload/fugitive.vim#L2894-L2908

It probably makes sense to mention here that in the original commit there were [no `empty(push)`][a], and that way it worked. But it made its way into the history [with `empty(push)`][b]. Which made it useless. From what I can tell.

Now, what is `push` used for? For the value in the header:

https://github.com/tpope/vim-fugitive/blob/2febbe1f00be04f16daa6464cb39214a8566ec4b/autoload/fugitive.vim#L2873-L2875

and as a reference point for the unpushed/unpulled sections. When there are no remotes, it makes sense for `push` to be empty for both use cases. Then `push`/`pull` in the header are not shown. And only the third unpushed section is shown.

So my suggestion is to not set `push` unless `has_remotes`. Which affects only the no-remotes case. What do you say? Along the lines of:

```diff
-    if push_default ==# 'upstream'
-      let push = pull
-    else
-      let push = len(branch) ? (push_remote ==# '.' ? '' : push_remote . '/') . branch : ''
-    endif
+    let has_remotes = len(filter(keys(config), 'v:val =~# "^remote\\.[^.]\\+\\.url$"'))
+    if has_remotes
+      if push_default ==# 'upstream'
+        let push = pull
+      else
+        let push = len(branch) ? (push_remote ==# '.' ? '' : push_remote . '/') . branch : ''
+      endif
+    else
+      let push = ''
+    endif
```

[a]: https://github.com/tpope/vim-fugitive/pull/1977/files#diff-10365a17ff115b36cc49bc50063bc922b573a739af8366cff7dd04f0a514ce8fR2854
[b]: https://github.com/tpope/vim-fugitive/commit/70251a915f4899980d5a53a566e180761a81d911#diff-10365a17ff115b36cc49bc50063bc922b573a739af8366cff7dd04f0a514ce8fR2854

**Comment by tpope** [comment] 2023-02-18 01:34
> `fugitive` doesn't show unpushed sections. One solution:
> 
> ```diff
> -if empty(pull) && empty(push) && empty(rebasing)
> +let has_remotes = len(filter(keys(config), 'v:val =~# "^remote\\.[^.]\\+\\.url$"'))
> +if empty(pull) && (empty(push) || !has_remotes) && empty(rebasing)
>    call s:AddLogSection('Unpushed to *', [head, '--not', '--remotes'])
>  endif
> ```

What happens when a remote exists that isn't named `origin`? I don't understand why _no_ remotes should be a special case.

**Comment by x-yuri** [comment] 2023-02-19 08:16
Well, because noone suggested a better solution yet. You suggested to not default to `origin`, and that'd probably be nice if it could resolve the issue, but I can't picture how.

The way I see it, there are basically two ways: to decide for the user, or let the user decide. AFAICT you don't like settings and that seems to make you the former kind of a person (which might be good, or bad if taken to the extreme). Or lean that way. Which is why I suggested the solution I suggested. It might be not flawless. But it resolves the issue and should work most of the time. When you add a remote, you get upstreams and can rely on the first two unpushed sections.

The latter way is either to add a setting (e.g. `fugitive.mode`, `local` or `public`) or ability to switch between the status buffer modes using the keyboard.

**Comment by tpope** [comment] 2023-02-19 10:43
> Well, because noone suggested a better solution yet. You suggested to not default to `origin`, and that'd probably be nice if it could resolve the issue, but I can't picture how.

If the repo has no remotes, then it necessarily follows that the current branch does not have a configured remote. And if the branch doesn't have a configured remote, then it will default to `origin`. The things that could be adjusted by changing the `origin` default are a superset of the things that could be adjusted by adding a special "no remotes" case.

> But `fetch_remote ==# ''` -> `push ==# '/master'`

When I said "alter this conditional", it was a starting point, not a self contained solution. Arriving at a broken `/master` ref isn't a dead end, it's the next thing to fix.

**Comment by x-yuri** [comment] 2023-02-21 17:51
> When I said "alter this conditional", it was a starting point, not a self contained solution. Arriving at a broken /master ref isn't a dead end, it's the next thing to fix.

Don't take me wrong, I was trying to follow your suggestion. But let me try to be more flexible about it. I still don't see how changing that conditional might help, but we can not set `push` unless there's `remote.<push_remote>.url`:

```diff
diff --git a/autoload/fugitive.vim b/autoload/fugitive.vim
index b1ffa37..ebfc148 100644
--- a/autoload/fugitive.vim
+++ b/autoload/fugitive.vim
@@ -2814,16 +2814,21 @@ function! fugitive#BufReadStatus(...) abort
     if empty(push_remote)
       let push_remote = fetch_remote
     endif
+    let push_url = FugitiveConfigGet('remote.' . push_remote . '.url', config)
 
     let push_default = FugitiveConfigGet('push.default', config)
     if empty(push_default)
       let push_default = fugitive#GitVersion(2) ? 'simple' : 'matching'
     endif
+    if len(push_url)
       if push_default ==# 'upstream'
         let push = pull
       else
         let push = len(branch) ? (push_remote ==# '.' ? '' : push_remote . '/') . branch : ''
       endif
+    else
+      let push = ''
+    endif
 
     if isdirectory(fugitive#Find('.git/rebase-merge/'))
       let rebasing_dir = fugitive#Find('.git/rebase-merge/')
```

What do you think?

**Comment by tpope** [comment] 2023-02-22 16:51
> > When I said "alter this conditional", it was a starting point, not a self contained solution. Arriving at a broken `/master` ref isn't a dead end, it's the next thing to fix.
> 
> Don't take me wrong, I was trying to follow your suggestion. But let me try to be more flexible about it. I still don't see how changing that conditional might help

```diff
diff --git i/autoload/fugitive.vim w/autoload/fugitive.vim
index 4dd2e10b..611ffd8d 100644
--- i/autoload/fugitive.vim
+++ w/autoload/fugitive.vim
@@ -2810,7 +2810,7 @@ function! fugitive#BufReadStatus(...) abort
       let push_remote = FugitiveConfigGet('remote.pushDefault', config)
     endif
     let fetch_remote = FugitiveConfigGet('branch.' . branch . '.remote', config)
-    if empty(fetch_remote)
+    if empty(fetch_remote) && !empty(FugitiveConfigGet('remote.origin.url', config))
       let fetch_remote = 'origin'
     endif
     if empty(push_remote)
@@ -2823,6 +2823,8 @@ function! fugitive#BufReadStatus(...) abort
     endif
     if push_default ==# 'upstream'
       let push = pull
+    elseif empty(push_remote)
+      let push = ''
     else
       let push = len(branch) ? (push_remote ==# '.' ? '' : push_remote . '/') . branch : ''
     endif
```

This, this is how it could help. If you avoid the original sin of using `origin` as the default remote when it doesn't exist, and address the emergent edge case that causes `/master`, everything falls into place.

**Comment by tpope** [comment] 2023-03-06 01:15
Okay, I've thought it through, and here's what I have decided to change:

* If neither remote ref exists (e.g., a brand new remote repository), then falling back to `Unpushed to *` is reasonable. (Actually, for the _brand new remote repository_ case only, I'd like to show `Unpushed to origin/master` with a full history, but it's hard to distinguish that from other cases.)
* If neither remote ref is _defined_ (e.g., there's no configured remote), then we shouldn't show anything. To put it another way, we shouldn't show `Unpushed to *` if there's no sensible definition of `*`. I don't want an `Unpushed` section that's by definition always the complete history.

I've pushed up an implementation of this. It precipitated a pretty big refactor so there may be edge cases to iron out.

**Comment by x-yuri** [comment] 2023-03-09 10:08
I'd say your explanation is a bit misleading. First, I took "brand new remote repository" as "brand new repository." But apparrently you mean a case where you create a remote repository and want to push to it. And the "neither remote ref" part. It looks like it's not always about refs. As long as a remote is defined (added), the `Unpushed to *` section is shown (or might be shown). Defining a ref sounds like defining an upstream (branch).

Apparently you want to show `Unpushed to *` only when there's an empty remote repository, defined locally.

And one might say that adding (defining) a remote expresses intent to push. Before that there's no sense in unpushed sections. But I wonder if you ever start a repository locally and need to change the history?

Anyways, I can use that as an escape hatch: define a dummy remote to make it show the history.

> we shouldn't show `Unpushed to *` if there's no sensible definition of `*`

Speaking of which, what's the definition of `*`? If an unknown/undecided destination, maybe `?` would be a better fit?

**Comment by tpope** [comment] 2023-03-09 18:41
> Speaking of which, what's the definition of `*`? If an unknown/undecided destination, maybe `?` would be a better fit?

Let's start by clearing this up. The `*` is the `*` in `git branch --remote --list '*'`. `Unpushed to *` means "Unpushed to _anywhere_". It's not unknown/undecided.

> I'd say your explanation is a bit misleading. First, I took "brand new remote repository" as "brand new repository" (a local one). But apparently you mean a case where you create a remote repository and want to push to it.

Misleading? More like misreading. :smirk:

Also note that this parenthetical isn't describing any actual behavior, just me musing about something I wish I could do but couldn't.

> And the "neither remote ref" part. It looks like it's not always about refs. As long as a remote is defined (added), the `Unpushed to *` section is shown (or might be shown). Defining a ref sounds like defining an upstream (branch).

More precisely, it's not if _any_ remote is added, it's when an `origin` remote is added. If we're on branch `foo`, and we add an `origin` remote, then both the push and upstream ref become `origin/foo`. Because Git itself defaults to `origin` if it exists, so do we.

So it is indeed ultimately about refs. The presence of an `origin` remote just gives us a default value for those refs.

> Apparently you want to show `Unpushed to *` only when there's an empty remote repository, defined locally.

Setting aside what I might "want" to do, there is no special behavior for an empty repository, just for an upstream ref that's nowhere to be found. If the upstream ref is `origin/foo`, and `origin/foo` doesn't exist, then the best we can do is say "hey, I can't show you what's not pushed to `origin/foo`, since that doesn't exist yet, so here's everything that hasn't been pushed anywhere, ever, since that's probably the stuff you're actually working on."

> And one might say that adding (defining) a remote expresses intent to push. Before that there's no sense in unpushed sections. But I wonder if you ever start a repository locally and need to change the history?

Yes. Usually the time between creating a repository and adding a remote is pretty short, but I do indeed occasionally start working on something far before I'm ready to push it anywhere.

I just don't think "show me the complete history of the repository with a nonsense heading" is a good solution to that.

> Anyways, I can use that as an escape hatch: define a dummy remote to make it show the history.

Indeed, the fact you can opt in to a goofy behavior with some goofy configuration has a certain elegance to it.

**Comment by x-yuri** [comment] 2023-03-27 07:25
> Misleading? More like misreading. ;)

You got me there :) But complex explanations are easy to misread. Anyways, I think you're starting from the end. And the beginning is, you want to avoid showing the complete history. This makes you invent the "no remote, no section" rule. And then you say, there's no sensible definition of `*`.

If you mean that "always the complete history" is not sensible, then first, it's not always the complete history. It's not always the complete history when the target ref is [defined, but doesn't exist][b]. But also it's not always the complete history when the target [ref is undefined][a]. Although such cases must be rare.

Second, not everybody would agree. If you're just starting out, and it's taking a while, you might need to amend the history. If you never intend to push it anywhere, then... "only wimps use tape backups..." comes to mind :) (not to be taking seriously) In any case, you [never show][c] the complete history.

You might say that "unpushed" makes no sense when there's nowhere to push, but you're not pushing, you're listing. Or at least there are more than one way to look at it. It obviously makes no sense when the user never intends to push, but I think that's rare, or the repository is thrown away before the history becomes big.

So let's not talk about what is sensible. Let's rather talk about the fact that you want to avoid listing the complete history.

Which makes me think... when there are no remotes, you can show an "unmerged into `*`" section instead. You likely don't want to hardcode the `master`/`main` branches in this case, but you can list the commits that are unmerged into any other branch. You still can't avoid listing the complete history in some cases, but... at least you tried :)

I occasionally mark a commit with a ref (a branch) to know which part of the branch I consider stable. (And start unstable commit messages with "~ " for that matter.) But I'm not sure you want to even start thinking in this direction. Like adding a setting to know where the stable part of the branch ends.

> More precisely, it's not if any remote is added, it's when an `origin` remote is added.

Well, AFAICS one can add a remote `whatever`, and set `branch.master.remote = whatever`. That is, it can be any remote after all, you just need to make it the remote, where `git push` would push.

On a side note, splitting it into ref defined/exists cases looks... more elegant (?), but it's more complex, because you need to define "defined." So I'm not sure I'd have chosen your way of explaining it, but... whatever.

> Indeed, the fact you can opt in to a goofy behavior with some goofy configuration has a certain elegance to it.

Elegance? I'd say it's nice to have an escape hatch when dealing with a benevolent dictator :)

And while I'm at it, let me put here what needs to be added to `.git/config`:

```
[remote "dummy"]
	fetch = +refs/heads/*:refs/remotes/dummy/*
[branch "master"]
	remote = dummy
```

[a]: https://gist.github.com/x-yuri/12910ba7394e96f179dc7430f05f80f8#file-a-md
[b]: https://gist.github.com/x-yuri/12910ba7394e96f179dc7430f05f80f8#file-b-md
[c]: https://github.com/tpope/vim-fugitive/blob/9acbad1335ee6f30a8497733dcb2373c4550c8a2/autoload/fugitive.vim#L2935
