### ISSUE TITLE
Navigating to commit doesn't work on Arch Linux if ~/.vimrc exists

### ISSUE THREAD

**Issue by kpcyrd** [tpope/vim-fugitive#1915] opened 2022-01-04 13:08 UTC
## Steps to reproduce

```
sudo pacman -S vim vim-fugitive
X=`mktemp -d`
export HOME="$X"
cd
touch .vimrc
git clone https://github.com/tpope/vim-fugitive
cd vim-fugitive
vim README.markdown

:Git blame
<enter>
```

Instead of navigating to this commit vim only moves the cursor down one line (the default when pressing enter in normal mode).

The plugin is working correctly if ~/.vimrc doesn't exist, but any config (even if empty) causes this issue somehow, likely because some kind of default isn't loaded from the system config then.

vim version: `8.2.3890-1`
vim-fugitive version: `3.4-2`

**Comment by tpope** [comment] 2022-01-04 13:20
Can't reproduce on my machine. Haven't gone to the trouble of setting up Arch. I recommend adding `source $VIMRUNTIME/default.vim` to your empty vimrc and see if the issue goes away. If so, have a look at that file and see if you can narrow down the relevant portion that prevents the issue.

**Comment by tpope** [comment] 2022-01-04 13:25
Also, 3.4 is two stable versions old. Might want to try the latest.

**Comment by kpcyrd** [comment] 2022-01-04 13:37
You can reproduce this in docker using:
```
docker pull archlinux
docker run -it --rm archlinux

pacman -Sy vim vim-fugitive git
X=`mktemp -d`
export HOME="$X"
cd
touch .vimrc
git clone https://github.com/tpope/vim-fugitive
cd vim-fugitive
vim README.markdown

:Git blame
<enter>
```

I've tried your suggestion and got:
```
[root@5fb5fb3e3693 vim-fugitive]# cat > ../.vimrc 
source $VIMRUNTIME/default.vim
[root@5fb5fb3e3693 vim-fugitive]# vim README.markdown
Error detected while processing /tmp/tmp.IpAcaMoUlz/.vimrc:
line    1:
E484: Can't open file /usr/share/vim/vim82/default.vim
Press ENTER or type command to continue
```

This works though (likely what you meant anyways):
```
[root@5fb5fb3e3693 vim-fugitive]# cat > ../.vimrc 
source $VIMRUNTIME/defaults.vim
[root@5fb5fb3e3693 vim-fugitive]# vim README.markdown
```

Navigating to the commit works with that line, so it seems vim-fugitive is depending on some kind of setting (this is still with 3.4 though).

Paging Arch Linux vim people @anthraxx @wahrwolf

**Comment by tpope** [comment] 2022-01-04 13:43
That should have been `defaults.vim`.

**Comment by tpope** [comment] 2022-01-04 13:45
Oh yes, you got that far. See if you can figure out which setting. I don't have any special insight here, but my first guess would be `filetype plugin indent on`.

**Comment by tpope** [comment] 2022-01-04 13:49
Yeah that's definitely it. This was resolved in https://github.com/tpope/vim-fugitive/commit/30933405bbc77877d714260f4ad1cd4dadf34532.

**Closed by tpope** 2022-01-04 13:49 UTC
