### ISSUE TITLE
Cannot commit when using the :Gstatus window

### ISSUE THREAD

**Issue by ajh17** [tpope/vim-fugitive#592] opened 2015-01-11 23:58 UTC
Hi,

When I have a file modified, I run :Gstatus, stage the file and then press `C` to commit the file.

However, I get the following error when I do:

`Error detected while processing function <SNR>11_Commit:`
`E16: Invalid range: 3wincmd+`

This also happens when I only have fugitive.vim installed and no other plugins, and also with a minimal vimrc with only:

 ```vim
execute pathogen#infect()
filetype plugin indent on
```

EDIT: Oh and it also does not commit the file if you type in a commit message after the error and save.

**Comment by ajh17** [comment] 2015-01-12 05:43
Found the issue. Apparently this is a vim problem.

Issue is present in vim 7.4.567. When I used vim 7.4.488, I could not reproduce the issue, but could on 7.4.567 every time (using the exact same config).

I looked through the list of patches in [this](http://ftp.vim.org/pub/vim/patches/7.4/README) Readme and found patch 565 may be the culprit:  `7.4.565  some ranges are not checked to be valid`

**Comment by djmaze** [comment] 2015-01-14 12:54
Same problem here (using the same vim version).

**Comment by tpope** [comment] 2015-01-14 18:02
Dupe of #591. Feel free to submit a workaround.

**Closed by tpope** 2015-01-14 18:02 UTC
