### ISSUE TITLE
git-crypt support?

### ISSUE THREAD

**Issue by juligreen** [tpope/vim-fugitive#1509] opened 2020-04-02 16:27 UTC
If I try to use `:Gdiffsplit` in a project that is encrypted with git-crypt, it always tries to diff with an encrypted file.

If i do a git diff or a git difftool on the commandline it works properly.
Is it possible to configure fugitive to work properly with git crypt?

**Comment by Parasrah** [comment] 2020-04-02 19:42
this seems to be a duplicate of #1508, albeit with more info

**Comment by tpope** [comment] 2020-04-02 20:03
We currently use `git cat-file` to populate the diff buffer. If you can provide a ore appropriate command to swap in it's possible we could support it.

**Closed by tpope** 2020-04-02 20:03 UTC

**Comment by YorikSar** [comment] 2021-09-10 19:55
@tpope Since git 2.11 ([released in 2016](https://github.com/git/git/releases/tag/v2.11.0)) you [can](https://github.com/git/git/commit/b9e62f60115c75c5be5de593862925c8b8d7e683) pass `--filter` instead of `blob` to `git cat-file` and it will process it with filters if applicable, including `git-crypt`. I think it should be enough replacing `blob` with `--filter` on lines 2112 and 2955 in `autoload/fugitive.vim`, but I don't really know if it will break smith else.

If you have to support older Git, maybe add an option for that? Like "supported Git version" or smth.

**Comment by tpope** [comment] 2021-09-10 20:09
The only breakage I can think of is that for the second case, the rev is not guaranteed to contain a `:path`. To address the path issue and the version issue in one go, try `rev =~# ':' && fugitive#GitVersion(2, 11) ? '--filters' : 'blob'`.

Please try the change out locally for a week or so and report back on your experience.

**Comment by YorikSar** [comment] 2021-09-13 09:54
Thanks for the direction. I've created commit YorikSar/vim-fugitive@58c6f2f and will test it for some time (I don't use git-crypt a lot, so it'll take about a month to be sure), then will create a pull request. Feel free to comment on that commit in the mean time.

**Comment by tpope** [comment] 2021-09-13 16:51
> Limitations:
> - staging/unstaging separate hunks (ala "git add -p") doesn't work, because "git apply" doesn't know about filters, same as "git add -p".

Is this a limitation related to your patch, or just of using git-crypt with Fugitive in general?

**Comment by YorikSar** [comment] 2021-09-13 17:01
It's a limitation of the git-crypt in general. `git add -p` (even without vim-fugitive) always complains that the encrypted file is binary and exits.

**Comment by tpope** [comment] 2021-09-13 17:24
Alright let's ditch that from the commit message before sending a PR then just to minimize confusion.

And on that note, send a PR whenever, a release isn't imminent so your light testing is probably good enough.

**Comment by YorikSar** [comment] 2021-09-13 20:10
Ok, you're the boss! Created #1837.
