### ISSUE TITLE
pathspec did not match any file(s) known to git

### ISSUE THREAD

**Issue by amateo** [tpope/vim-fugitive#438] opened 2014-02-18 09:49 UTC
Hello,

  Maybe this is not directly related with fugitive, but with git, but my problem is when using git from vim (with fugitive plugin).

  This is my problem: I have a few git repositories, not just once, all of them are in the same directory (let's call ~/git for the parent directory and repositories are ~/git/repo1 and ~/git/repo2). Since I often works (simultaneously) with a few of them, I usually open files with vim from the parent directory.

  My problem is that in this scenario, I can't use git from vim, for example if I make:
- cd ~/git
- vim repo1/README
- (in vim) Gcommit %
  
  The commit buffer is opened, but when I write it and commit is actually done, I get the error: **fugitive: error: pathspec 'repo1/README' did not match any file(s) known to git.**
  
  I know the problem is that my current directory is ~/git and I don't have any repository (~/git/.git directory). But I wonder if there is some option in fugitive that could help with this problem.

PS: I have tried autochdir vim option. With this, there is no problem, but I don't like autochdir (it involves a mess with buffer's path) and I would like a solution without this mess.

**Comment by markstos** [comment] 2017-11-18 17:01
I still ran into this today when using `:Gcommit -n`. It seems the problem as described by @tpope still exists:

> the problem seems to be % is expanded relative to the cwd but the command is called relative to the repository root.

That was definitely my case: Was running the `:Gcommit` command from a folder, not the project root.

Is some alternate approach recommended when I want to "add" and "commit" in a single step?

It seems #497 may be dupe of this issue.

**Comment by tpope** [comment] 2017-11-18 22:50
`<C-R><C-G>` inserts the repo relative path to the file and can be used as an alternative to `%`. A proper fix is somewhat tricky, as you need to replace not just `%` but also constructions like `%:h`. [There's a similar replacement in `:Gmove`](https://github.com/tpope/vim-fugitive/blob/7c9b87a3c3ef4b53425aca4a27e11a7359caae9f/plugin/fugitive.vim#L1887) that might be a useful starting point.

**Comment by tpope** [comment] 2019-08-16 07:25
Fixed.

**Closed by tpope** 2019-08-16 07:25 UTC
