### ISSUE TITLE
fugitive: "origin' is not a supported remote

### ISSUE THREAD

**Issue by mohammed-elhakim-sociomantic** [tpope/vim-fugitive#844] opened 2016-10-11 15:44 UTC
Hey, I know this has been discussed numerous times. But I am still getting this error when I do `:Gbrowse`:
`fugitive: "origin' is not a supported remote`

Where do I even start debugging it?

**Comment by SevereOverfl0w** [comment] 2016-10-12 15:41
Can you share your `git remote -v`?

**Comment by mohammed-elhakim-sociomantic** [comment] 2016-11-04 12:48
origin	ssh://git@github.com/company/project.git (fetch)
origin	ssh://git@github.com/company/project.git (push)

**Comment by tpope** [comment] 2016-11-04 22:27
Are the quotes really mismatched like that?

**Comment by mohammed-elhakim-sociomantic** [comment] 2016-11-07 10:00
@tpope you mean for `"origin'` instead of something like `"origin"` or `'origin'`?
Yes... :confused:

**Comment by adamdicarlo** [comment] 2016-11-12 23:12
Mine says `".' is not a supported remote`

```
origin	git@github.com:org/repo (fetch)
origin	git@github.com:org/repo (push)
```
git version 2.10.0

**Comment by adamdicarlo** [comment] 2016-11-12 23:20
Interesting... after running
```
git branch --set-upstream-to origin/<branchname>
```

running `:Gbrowse` now gives

```
"origin' is not a supported remote
```

maybe the remote has to be in `git+ssh://` format?

**Comment by tpope** [comment] 2016-11-14 00:04
Well, I fixed the quotes at least. :smile:

It should support that URL format but try changing it to the `https://` version to rule it out as a cause.

**Comment by mohammed-elhakim-sociomantic** [comment] 2016-11-14 14:50
Tried changing it to `git+ssh` and `https` both still give the same error.

**Comment by rawaludin** [comment] 2016-12-03 06:05
Just installed fugitive today. Having same issues. Gbrowse keep giving me `fugitive: 'origin' is not a supported remote'.

my remote is:
```
origin  ssh://git@github.com/KWRI/hydrogen-crm-foundation.git (fetch)
origin  ssh://git@github.com/KWRI/hydrogen-crm-foundation.git (push)
```

**Comment by rawaludin** [comment] 2016-12-03 06:06
Just installed fugitive today. Having same issues. Gbrowse keep giving me `fugitive: 'origin' is not a supported remote`.

my remote is:
```
origin  ssh://git@github.com/project/repo.git (fetch)
origin  ssh://git@github.com/project/repo.git (push)
```

**Comment by SevereOverfl0w** [comment] 2016-12-06 12:23
@adamdicarlo your issue might be because the URL doesn't end in `.git`

@rawaludin The `ssh://git@` format isn't supported. https://github.com/tpope/vim-rhubarb/pull/16 there's a PR to add support.

**Comment by codingluke** [comment] 2016-12-22 08:17
Having the same issue here with *Github Enterprise*. I don't know if this is already supported, I wanted to use this feature the first time an got `fugitive: '.' is not a supported remote`

My `git remote -v` structure is:

```
origin  git@github.example-domain.de:company/reponame.git (fetch)
origin  git@github.example-domain.de:company/reponame.git (push)
```

**Comment by SevereOverfl0w** [comment] 2016-12-22 17:22
@codingluke You should install https://github.com/tpope/vim-rhubarb the installation covers enterprise installations.

**Comment by elsonico** [comment] 2016-12-24 02:47
I have the same issue and just installed vim-rhubarb, but it still says:

fugitive: 'origin' is not a supported remote.

**Comment by codingluke** [comment] 2016-12-27 02:02
@SevereOverfl0w thx, it is working now for me, with _Github Enterprise_

**Comment by mohammed-elhakim-sociomantic** [comment] 2016-12-27 10:36
I am not using Github Enterprise. Installed vim-rhubarb, but still getting the same error.

**Comment by elsonico** [comment] 2016-12-27 18:03
I actually have to correct my mistake on my previous post. I'm not connected to GitHub Enterprise, but to Atlassian Stash, which isn't the same thing, now that I noticed.

**Comment by SevereOverfl0w** [comment] 2017-01-05 12:30
@mohammed-elhakim-sociomantic vim-rhubarb will work for your original remote once https://github.com/tpope/vim-rhubarb/pull/16 is merged.

**Comment by chipbroze** [comment] 2017-04-26 16:56
I was having this problem, and traced it back to my version of git (2.5.0).  Fugitive gets the url using the command "git remote get-url [REMOTE]", which is not a valid command in 2.5.0.

**Comment by tpope** [comment] 2017-04-26 17:09
I don't like abandoning support for old Git versions without due cause so I pushed a fix for that. Hopefully that takes care of everyone else who hasn't been addressed. Speak up if not.

**Closed by tpope** 2017-04-26 17:09 UTC

**Comment by mohammed-elhakim-sociomantic** [comment] 2017-04-26 17:23
Works! Thanks!

**Comment by yakschuss** [comment] 2017-05-30 00:16
I just updated, having the same issue. Let me know if there's anything I can do to reproduce.

**Comment by tpope** [comment] 2017-05-30 00:20
What is `git config remote.origin.url` and your Git version?

**Comment by yakschuss** [comment] 2017-05-30 00:26
```
→ git config remote.origin.url
git@github.com:OrgName/RepoName.git
```
```
→ git --version
git version 2.5.3
```

Sorry about the org name stuff, pretty sure I can't share that 😕

**Comment by tpope** [comment] 2017-05-30 00:53
Can you check `:echo fugitive#git_version() =~# '^[01]\.|^2\.[0-6]\.'` to make sure it's `1`? Then check `:echo fugitive#repo().git_chomp('config','remote.origin.url')`.

Oh, and confirm you have rhubarb.vim installed.

**Comment by yakschuss** [comment] 2017-05-30 00:58
The version is 0, everything else is as expected. I just did a `PlugUpdate` before posting, what do you recommend here?

**Comment by tpope** [comment] 2017-05-30 01:18
Okay there's the problem. The regexp was missing a backslash. Should be good to go now.

**Comment by yakschuss** [comment] 2017-05-30 01:20
Nice! That works perfectly. Thanks!!

**Comment by AravK** [comment] 2017-09-01 11:18
Still having issue.
`git --version`: `2.14.1`
`git config remote.origin.url`: `ssh://git@github.com/AravK/ProjectName` (no `.git`)
Is the missing `.git` the issue?

**Comment by mikaelz** [comment] 2017-09-01 12:29
I also have the issue with
```
origin	git@bitbucket.org:me/example.com.git (fetch)
origin	git@bitbucket.org:me/example.com.git (push)
```

Tried with another remote
```
origin  https://github.com/tpope/vim-fugitive.git (fetch)
origin  https://github.com/tpope/vim-fugitive.git (push)
```
It opens a new tab browser at https://github.com/tpope/vim-rhubarb :)

**Comment by SevereOverfl0w** [comment] 2017-09-01 13:19
@mikaelz I cannot reproduce your issue with vim-fugitive converting to vim-rhubarb for fugitive or any other github urls.

@AravK I just tested with a url like yours: without  the `.git`, and the `:Gbrowse` command worked.
My git version also matches yours.

**Comment by florian-devolute** [comment] 2017-10-11 15:14
I had the same problem because I was using a different ssh key and configured my origin in a way to use that ssh key. I fixed this by changing the remote to https://github.com/...

**Comment by kevintaylor** [comment] 2017-12-29 14:43
FYI, I was getting the "fugitive: 'origin' is not a supported remote" message using bitbucket with the bitbucket fugitive extension. Mac High Sierra, GVim and terminal Vim.

$ git --version
git version 2.15.0

$ git remote -v
origin	user@bitbucket.org:user/proj.com.git (fetch)
origin	user@bitbucket.org:user/proj.com.git (push)

To get Gbrowse to work, I needed to add https:// in .git/config, so
$ git remote -v
origin	https://user@bitbucket.org:user/proj.com.git (fetch)
origin	https://user@bitbucket.org:user/proj.com.git (push)

**Comment by tpope** [comment] 2017-12-29 20:59
Individual plugins decide what URLs they will and won't accept.  So in the above comment, for example, it is the bitbucket plugin that is declining to handle `user@bitbucket.org:...`.

Rhubarb (which I maintain) should accept GitHub URLs with out without a `.git` suffix, so feel free to open an issue there if you have a reproducible problem.

**Comment by gbbr** [comment] 2018-05-24 07:59
Is there any way I can use this plugin if my remote is not called `origin`?

**Comment by tpope** [comment] 2018-05-24 16:13
It should work for the remote being tracked for the current branch, regardless of name. You can also `:Gbrowse myremote/mybranch:%` to force any remote.
