### ISSUE TITLE
precommit hook show terminal escape characters in output

### ISSUE THREAD

**Issue by NickyTope** [tpope/vim-fugitive#1460] opened 2020-02-07 04:25 UTC
I'm using some npm packages for precommit linting (husky and lint-staged).

lint-staged attempts to rewrite characters in place in the terminal by using escape characters, is there anyway i can get the fugitive window that precommit output shows in to either support or drop these escape characters?

![image](https://user-images.githubusercontent.com/955302/74001048-3cbf3800-49be-11ea-9c3f-fdb57a891d26.png)

**Comment by tpope** [comment] 2020-02-07 04:28
Dupe of #1446. Fixed in https://github.com/okonet/lint-staged/issues/781.

**Closed by tpope** 2020-02-07 04:28 UTC

**Comment by NickyTope** [comment] 2020-02-07 04:29
Thanks, did search but obviously missed this one, appreciate the lightning fast response
