### ISSUE TITLE
Use of vim-rails commands in Git window

### ISSUE THREAD

**Issue by alibby** [tpope/vim-fugitive#2110] opened 2023-02-04 12:38 UTC
Sometime recently commands like `Econtroller` from vim-rails stopped working when focus is on the `:Git` window.  My workaround is to `--` to get to the working tree where these commands work.  Not sure if this is intended or if it's a chnage with vim-fugitive or vim-rails that caused it.  Thanks for doing what you do.

**Comment by tpope** [comment] 2023-02-05 00:34
The `:Git` window used to use `$GIT_DIR/index` as the filename, which meant plugins like rails.vim would see it as being inside the root of your Rails app. This was never really an intended behavior, and notably only worked when `$GIT_DIR` is inside of the work tree, excluding external work trees, submodules, and other weird edge cases, some of which Fugitive just couldn't support at all due to this design. In service of those weird edge cases (among other reasons), the `:Git` window now lives at a `fugitive://` URL. Since it's no longer coupled to the file system path, Rails.vim will no longer naturally see it as part of the repository, and there isn't really an unnatural way to achieve the same effect either.

Note the Git window is designed to persist until you close it. If you press `<CR>` to open a file, it switches to the other window to open it. Rails.vim commands _don't_ do this, and this in-congruence makes it arguable that not defining them is actually _fixing_ a bug.

**Closed by tpope** 2023-02-05 00:34 UTC

**Comment by cbartlett** [comment] 2023-02-09 21:45
I'm really glad this wasn't just me experiencing this regression, it's been driving me absolutely bananas. I have been doing `:e .` but I like `--` better, thanks @alibby. In my case, I almost exclusively work in apps where `$GIT_DIR` is inside of work tree. Any chance of a config setting or something that restores [this behavior](https://github.com/tpope/vim-fugitive/commit/9a13fc87c4ab83ea81e71ccad9b846a5eb31a998)?
