### ISSUE TITLE
Interactive git rebase issues (Vim/Neovim)

### ISSUE THREAD

**Issue by siphiuel** [tpope/vim-fugitive#1329] opened 2019-09-03 20:24 UTC
Hi!

I've created a repo with 3 commits (`Commit 1`, `Commit 2`, `Commit 3`). Entering Vim (8.1.1950) and running `:Git rebase -i HEAD~2` shows an interactive git rebase window with commits 2 and 3. I squash commit 3 and `:wq`. This shows the error:
```
Error detected while processing function <SNR>53_Command[3]..fugitive#Command[17]..<SNR>53_CommitSubcommand:
line   72:
E242: Can't split a window while closing another
```

Press enter, then run `:G`. This shows another error: `E685: Internal error: hash_add()
E931: Buffer cannot be registered`. But after pressing Enter status buffer appears just fine. In which i see:
```
Rebasing master (2)
stop 8de66c26f3b Commit 3
done 22947282b67 Commit 2

Staged (1)
M new
```
Running `:Git rebase --continue` afterwards completes the rebase, but there are 3 commits still.

Running in Neovim (0.3.8) does not show any errors, but rebase has no effect either.

Maybe I'm doing something terribly wrong. This used to work though some time ago.

I can try fixing it myself, but some directions as to where to look would be really helpful.

Thanks for the wonderful plugin I've been using for so many years.

**Comment by tpope** [comment] 2019-09-03 21:13
At first glance it looks like https://github.com/vim/vim/commit/1417c766f55e5959b31da488417b7d9b141404af might be biting us. But that's a little weird because we wait till `BufEnter` to fire. You can start by confirming that https://github.com/tpope/vim-fugitive/blob/a45e2c6d577ca3ec6c10ed82465aa9650316f70c/autoload/fugitive.vim#L3647 is the line that causes the error.

**Comment by thornomad** [comment] 2019-09-20 18:01
Don't mean to hijack this thread if it's unrelated (can open a new issue if I should), but am also having issues with interactive rebase and neovim.  Or maybe I'm just doing it wrong (sigh).

* `:Grebase --interactive HEAD~5`
* It opens a new split, and I change one of the `pick` settings to `reword`.  
* `:x<CR>`
* Window closes and a new one opens showing the commit. I make changes.
* `:x<CR>`

Everything seems to have worked (no errors) but in the end ... I am not seeing my commit message changes actually taking effect.  Thanks in advance for any help or guidance.

**Comment by tpope** [comment] 2019-09-20 23:30
Do operations other than reword work?

**Comment by thornomad** [comment] 2019-09-23 17:09
I just tested a `merge` and that worked without a hiccup.  Retested `reword` (as above) and still can't get it to stick.  If this is working for everyone else I will try and narrow down by running a minimal setup.  Thanks again.

**Comment by ToruIwashita** [comment] 2019-09-27 05:53
I also encountered the same problem.

If the following patch was applied, reword is worked. But it doesn't seem to be the correct fix, so I need help.

```
diff --git a/autoload/fugitive.vim b/autoload/fugitive.vim
index b954dc8..6684f7f 100644
--- a/autoload/fugitive.vim
+++ b/autoload/fugitive.vim
@@ -3590,7 +3590,7 @@ function! s:MergeRebase(cmd, bang, mods, args, ...) abort
           \ filereadable(fugitive#Find('.git/rebase-merge/done', dir)) &&
           \ get(readfile(fugitive#Find('.git/rebase-merge/done', dir)), -1, '') =~# '^[^e]'
       cclose
-      return 'exe ' . string(mods . 'Gcommit --amend -n -F ' . s:fnameescape(fugitive#Find('.git/rebase-merge/message', dir)) . ' -e') . '|let b:fugitive_commit_rebase = 1'
+      return 'exe ' . string(mods . 'Git commit --amend -n -F ' . s:fnameescape(fugitive#Find('.git/rebase-merge/message', dir)) . ' -e') . '|let b:fugitive_commit_rebase = 1'
     elseif !had_merge_msg && filereadable(fugitive#Find('.git/MERGE_MSG', dir))
       cclose
       return mods . 'Gcommit --no-status -n -t '.s:fnameescape(fugitive#Find('.git/MERGE_MSG', dir))
```

**Comment by tpope** [comment] 2019-09-27 11:22
Same problem as in same exact error message?

**Comment by ToruIwashita** [comment] 2019-10-01 06:08
When the following command is executed

```
:Grebase --interactive xxxxxxxx
```

The following error message is displayed, so I think it is the same error.

```
E242: Can't split a window while closing another
```

**Comment by tpope** [comment] 2019-10-01 13:57
See if you can confirm what I asked about in my first comment.

**Comment by odnoletkov** [comment] 2019-10-04 20:58
> At first glance it looks like [vim/vim@1417c76](https://github.com/vim/vim/commit/1417c766f55e5959b31da488417b7d9b141404af) might be biting us. But that's a little weird because we wait till `BufEnter` to fire.

Confirmed this caused the problem: it's parent [vim/vim@1417c76~1](https://github.com/vim/vim/commit/0aca293fedfd22d489297f7cbce6a7de86748151) works fine.

> You can start by confirming that
> 
> https://github.com/tpope/vim-fugitive/blob/a45e2c6d577ca3ec6c10ed82465aa9650316f70c/autoload/fugitive.vim#L3647
> 
> is the line that causes the error.

Yes this line causes the error

**Comment by tpope** [comment] 2019-11-24 06:36
Can someone test if tossing it in a `timer_start(0, ...)` works?

**Comment by odnoletkov** [comment] 2019-11-30 19:48
With this

```diff
diff --git a/autoload/fugitive.vim b/autoload/fugitive.vim
index 8f25832..2e5f8d5 100644
--- a/autoload/fugitive.vim
+++ b/autoload/fugitive.vim
@@ -3775,7 +3775,7 @@ augroup fugitive_merge
         \ endif
   autocmd BufEnter * nested
         \ if exists('s:rebase_continue') |
-        \   exe s:MergeRebase('rebase', 0, '', [getfsize(fugitive#Find('.git/rebase-merge/git-rebase-todo', s:rebase_continue)) > 0 ? '--continue' : '--abort'], remove(s:, 'rebase_continue')) |
+        \   call timer_start(0, {-> execute(s:MergeRebase('rebase', 0, '', [getfsize(fugitive#Find('.git/rebase-merge/git-rebase-todo', s:rebase_continue)) > 0 ? '--continue' : '--abort'], remove(s:, 'rebase_continue')))}) |
         \ endif
 augroup END
```

the error is gone and commit editor is shown for reword/squash commands. After I close it rebase completes but the result doesn't include any of the changes made – as described above.

**Comment by tpope** [comment] 2019-11-30 20:09
Does this mean that `getfsize()` is returning 0 or -1 and `git rebase --abort` is being called?

**Comment by odnoletkov** [comment] 2019-11-30 20:33
Yes – it returns 0 when closing editor for fixup/reword command

**Comment by tpope** [comment] 2019-11-30 22:20
That is not what I am seeing. Even if we're on the last step `git-rebase-todo` contains a blank line and the usual comments. Any guesses what's going wrong?

**Comment by odnoletkov** [comment] 2019-12-01 00:08
> Even if we're on the last step git-rebase-todo contains a blank line and the usual comments

My `.git/rebase-merge/git-rebase-todo` never contains blank lines or any comments – no matter if I am rebasing using fugitive or Git CLI. Only list or remaining commands.

In fugitive:

When I'm rewording any *single* commit which is not the last one (oldest) everything works as expected.

When I'm rewording the last commit:

* I'm prompted for the new message
* `.git/rebase-merge/git-rebase-todo` is empty (0 bytes)
* When I save and close the split rebase finishes with no changes applied

When I'm rewording any two commits:

* The first commit is updated just fine
* For the second commit rebase just stops w/o editor shown
* If I continue rebase, it completes with only the first commit updated

This is with:
* `timer_start(0, ...)`
* fugitive 67efbf66e0fcfd25e617d22892a7e9768bfd0f92
* git version 2.24.0 and empty config
* Vim 8.1 and empty config

**Closed** 2019-12-06 19:42 UTC

**Comment by odnoletkov** [comment] 2019-12-07 13:13
With some manual fixes to https://github.com/tpope/vim-fugitive/commit/b48a572475488572b738bf9c49726d63f7fa5e34 the 'reword last commit' issue is resolved.

But the 'reword two commits' issue does still exist:

> When I'm rewording any two commits:
> 
> * The first commit is updated just fine
> * For the second commit rebase just stops w/o editor shown
> * If I continue rebase, it completes with only the first commit updated

If I do multiple squashes instead of rewords it works w/o issues

**Comment by tpope** [comment] 2019-12-07 15:15
Works for me.

**Comment by odnoletkov** [comment] 2019-12-07 18:16
The problem is in this condition https://github.com/tpope/vim-fugitive/blob/6d4564a05e6d974ae05623338a4579ae63ba4243/autoload/fugitive.vim#L3702-L3703

For the first reword command in the rebase the .git/rebase-merge/amend file exists and Gcommit is called with the --amend flag.

For the second reword command it doesn't exist, no --amend flag is added and commit errors out with the 'nothing to commit, working tree clean' message.

Not sure why it doesn't repro for you, I am testing with empty configs and versions listed above

**Comment by tpope** [comment] 2019-12-07 20:00
I'm seeing exactly the same except the amend doesn't exist because the changes are staged.

**Comment by tpope** [comment] 2020-01-06 03:46
Try the `job` branch. I aim for it to ultimately replace `:Grebase` and several other custom commands.

**Comment by odnoletkov** [comment] 2020-01-09 01:25
In the `job` branch all of the above issues doesn't repro for me.

The only issue I found is every time before editor needs to be open for one of the reword/squash commands there is a hit-enter prompt *and* it takes two enter keystrokes to close it (or one keystroke which will be processed by Vim). Looks like a missing `:redraw` issue.

**Comment by tpope** [comment] 2020-01-09 05:15
We want one press enter prompt so the output can be viewed. The second one is seemingly caused by editing the next file from inside a timer. It goes away if we use the `BufEnter` event. But then we're back to E242 on newer versions. Goddammit.

One solution is to use the new `SafeState` event. That still leaves two months of patches that don't work, and shows a blank line where it should show the name of the newly loaded file. Another is to give up and use `tabedit`. I've pushed up both as separate commits to the `job` branch. I'm leaning towards the latter.

**Comment by odnoletkov** [comment] 2020-01-09 23:45
The issue with double hit-enter is fixed for me in both versions.

Just noticed another issue (with both versions). If I close the 'editor' split/tab with <kbd>ZZ</kbd>: git output is only shown during rebase – when the process stops the output is cleared and only hit-enter text is shown with blank lines under it. This works fine – output is preserved above the hit-enter line – if I close the editor with a command or a mapping.

**Comment by tpope** [comment] 2020-01-10 05:14
Fuck that, I'm switching to `feedkeys()`.

**Comment by odnoletkov** [comment] 2020-01-10 23:32
Can confirm https://github.com/tpope/vim-fugitive/commit/ede4a2f0e3b34d5b704bd87455955958eac5abe5 resolves all the above prompt issues.

Found another issue in the `job` branch. `:Git merge` in conflicted index doesn't load all conflicts in the quckfix like it used to but outputs an error:

> error: Merging is not possible because you have unmerged files.
> hint: Fix them up in the work tree, and then use 'git add/rm <file>'
>hint: as appropriate to mark resolution and make a commit.
> fatal: Exiting because of an unresolved conflict.

Bisects to https://github.com/tpope/vim-fugitive/commit/653478b7d1a725aaef38ba9c5511e7f5fea24aa9

**Comment by tpope** [comment] 2020-01-10 23:49
I think that's probably fine. We have `:Git mergetool` now which does a much better job at it which the user can manually invoke. *Sometimes* overriding the quickfix list is a weird interface, and the old behavior of always overriding it could be obnoxious.

There are a few other special cases - in particular `:Grebase --autosquash` forcing `--interactive` but skipping the initial edit - that I will look into restoring once I'm 100% sure this is the way forward.

**Comment by odnoletkov** [comment] 2020-01-11 00:20
> I think that's probably fine. We have `:Git mergetool` now which does a much better job at it which the user can manually invoke. _Sometimes_ overriding the quickfix list is a weird interface, and the old behavior of always overriding it could be obnoxious.

This makes sense, do you plan to update the <kbd>cm\<CR\></kbd> mapping then to call `:Git mergetool` in conflicted index?

**Comment by tpope** [comment] 2020-01-11 01:32
I wasn't thinking about the zero argument special case when I said that. I'll start by adding a warning and decide the ultimate course of action later.

I'm less worried about the unofficial `cm<CR>` map, but I'll add a new unofficial `cmt` map so at least there's a warning free replacement.

**Comment by odnoletkov** [comment] 2020-01-11 17:18
Also <kbd>rf</kbd> doesn't work and just outputs:

> Current branch master is up to date.

**Comment by tpope** [comment] 2020-01-12 00:02
That's the `:Grebase --autosquash` behavior i called out.

**Comment by tpope** [comment] 2020-01-15 06:08
`:Git rebase --autosquash` is fixed. Redirect further discussion to #1433.
